# Example Playbook written in YAML

# YAML Playbook file starts with three dashes

---

# Example targeting host
- name: Set up App Host
  hosts: localhost

# used to define where this playbook will run

  gather_facts: yes
# gathers facts/state of machine before running playbook

  become: true
# become is used to get root permission to perform tasks that may require admin access

  vars:
    ip_db:
      DB_HOST: 192.168.33.11

  environment: "{{ ip_db }}"

  tasks:
  - name: Update apt-get
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Installing git
    apt:
      name: git
      state: present

  - name: Installing nginx
    apt:
      name: nginx
      state: present

  - name: Synchronise app folder
    synchronize:
      src: /home/ubuntu/app
      dest: /home/ubuntu/
      recursive: yes

  - name: Synchronise nginx config folder
    synchronize:
      src: /home/ubuntu/nginx_config
      dest: /home/ubuntu/
      recursive: yes

  - name: Curl nodejs source
    shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

  - name: Install nodejs
    apt:
      pkg: nodejs
      state: present

  - name: Installing pm2 with npm
    npm:
      name: pm2
      global: yes

  - name: Remove default nginx config
    file:
      path: /etc/nginx/sites-available/default
      state: absent

  - name: Copy new nginx config
    copy:
      src: /home/ubuntu/nginx_config/proxy_config.conf
      dest: /etc/nginx/sites-available/default

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
      enabled: yes

  - name: Export DB_HOST environment variable
    shell: echo "export DB_HOST=172.31.38.233" >> ~/.bashrc

  - name: npm install all packages for app
    npm:

  tags: ['never', 'create_ec2']





